project:
  type: book
book:
  title: "JDemetra+ documentation"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
  author:
    - name: Anna Smyk (Coordinator)
      url: https://github.com/annasmyk
      affiliations:
        - name: Insee
          country: France
          city: Paris
          url: "https://www.insee.fr/fr/accueil"
    - name: Tanguy Barthelemy
      url: https://github.com/TanguyBarthelemy
      affiliations:
        - name: Insee
          country: France
          city: Paris
          url: "https://www.insee.fr/fr/accueil"
      role: "Author"
    - name: Maria Novas Filgueira
      url: https://github.com/maria-novas
      affiliations:
        - name: Ine
          country: Spain
          city: Madrid
          url: "https://www.ine.es/"
      role: "Collaborator"
    - name: Karsten Webel
      url: https://github.com/webelk
      affiliations:
        - name: Deutsche Bundesbank
          country: Germany
          city: Frankfurt
          url: "https://www.bundesbank.de"
      role: "Collaborator"
  date: "11/23/2023"
  page-navigation: true
  chapters:
    - index.qmd
    ##- example.qmd
    - G-how-to-use-this-book.qmd ## (#G-use-book)
    - G-news-v3-vs-v2.qmd ##(#v3-vs-v2)
    ##- G-jd-history.qmd ##(#g-jd-hist)
    - part: P_Algorithms.qmd ##(#part-A)
      chapters:
        - A-RegArima-Tramo-Modelling-Overview.qmd ## (#a-reg-a)
        - A-sa-overview.qmd ##(#sa-overview)
        - A-sa-pre-treatment.qmd ##(#sa-pre-t)
        - A-sa-X11-decomposition.qmd ##(a-sa-X11)
        - A-sa-seats-decomposition.qmd ##(#a-sa-seats)
        - A-sa-stl-decomposition.qmd ##(#a-sa-stl)
        - A-sa-bsm.qmd ##(#a-sa-bsm)
        - A-sa-hf.qmd ##(#a-sa-hf)
        - A-outlier-detection.qmd ##(#a-out-reg-ext)
        - A-calendar-correction.qmd ##(#a-cal)
        - A-benchmarking.qmd ##(#a-bench)
        - A-trend-cycle-estimation.qmd ##(#a-trend)
        - A-revision-analysis.qmd ##(#a-revs)
        - A-nowcasting.qmd ##(#a-now)
    - part: P_Tools.qmd ##(#part-T)
      chapters:
        - T-GUI-Overview.qmd ##(#t-gui-overview)
        - T-GUI-Data-Viz-TS-Tools.qmd ##(#t-GUI-tstools)
        - T-GUI-SA-Modelling-Features.qmd ##(#t-gui-sa)
        - T-GUI-Output.qmd ##(#t-gui-output)
        - T-r-packages.qmd ##(#t-r-packs)
        - T-Production-tools-cruncher-QR.qmd ##(#t-prod)
        - T-rev-policies-production.qmd ##(#t-rev-pol)
        - T-plug-ins.qmd ##(#t-plug-ins)
    - part: P_Methods.qmd ##(#part-T)
      chapters:
        - M-spectral-analysis.qmd ##(#m-spectrum)
        - M-reg-arima-modelling.qmd ##(#m-reg-a)
        - M-X11-decomposition.qmd ##(#m-X11)
        - M-SEATS-decomposition.qmd ##(#m-seats)
        #- M-sa-hf.qmd ##(#m-sa-hf)
        - M-Trend-Estimation-Local-Polynomials.qmd ##(#m-trend)
        - M-tests.qmd ##(#m-tests)
        - M-STL-decomposition.qmd ##(#m-stl)
        - M-state-space-framework.qmd ##(#m-ssf)
        - M-Temp-Disagg-Bench.qmd ##(m-bench)
    #     - references.qmd
bibliography: references.bib

format:
  html:
    theme: 
        - united
        - custom.scss
    css: styles.css
  pdf:
    mainfont: "DejaVu Sans"
    documentclass: scrreprt

editor: source
